// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {analyzer} from '../models';

export function Analyze(arg1:string):Promise<analyzer.Result>;

export function ReadFile(arg1:string):Promise<string>;

export function SelectFile():Promise<string>;
